version: '3.8'

services:
    blog:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '8890:80'
        volumes:
            - ./app:/var/www/html

    database:
        image: 'mariadb'
        restart: always
        environment:
            MYSQL_DATABASE: data
            MYSQL_ROOT_PASSWORD: password
        volumes:
#            # Pour lancer un dump automatiquement au montage du conteneur
           - ./database/dump.sql:/docker-entrypoint-initdb.d/dump.sql


    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - '8686:80'
        environment:
            - PMA_ARBITRARY=1
